### ISSUE TITLE
FRONTEND: /offers shows dummy data before loading sql results

### ISSUE THREAD

**Issue by shivamjindal** [shivamjindal/covid-help#18]
While the get request to the backend is still being completed, the website shows some sort of dummy data in /offers. Instead, users should just see "Loading...". If the backend returns an error, users should be redirected to a 404 page.

**Comment by ndjuice** [comment]
@shivamjindal what is /offers

**Comment by ndjuice** [comment]
@shivamjindal , resolved issue kind of, not opening a dummy listing, but now it rapidly shows "no current listings" (that is default if empty)

**Comment by ndjuice** [comment]
https://hackernoon.com/lazy-loading-and-preloading-components-in-react-16-6-804de091c82d
