### ISSUE TITLE
BACKEND: Database not successfully connecting after login

### ISSUE THREAD

**Issue by ndjuice** [shivamjindal/covid-help#21]
<img width="636" alt="Screen Shot 2020-03-25 at 9 36 17 PM" src="https://user-images.githubusercontent.com/15805196/77611333-4d7e2b80-6ee2-11ea-845d-68a5e18e3dab.png">

**Comment by shivamjindal** [comment]
Can you let me know exactly what you do to produce this error so that I can reproduce this?

**Comment by ndjuice** [comment]
- Laptop is shut
- Start the frontend / backend server
- Log-in
- No listings displayed
