### ISSUE TITLE
FE: Okta widget throwing error:  An instance of the widget has already been rendered. Call remove() first.

### ISSUE THREAD

**Issue by ndjuice** [shivamjindal/covid-help#53]
https://stackoverflow.com/questions/34779324/initialising-okta-signin-widget-a-second-time-in-a-single-page-webapp-throws-exc

**Comment by gmwill934** [comment]
In `useEffect`, use a clean up function and simple call the `remove` method.

```
return () => {
      oktaWidget.remove();
    };
```

**Comment by pitaman71** [comment]
I am seeing this error right now with the cleanup function in place.
